apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dwk-nats
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: dwk-nats
      sourceRef:
        kind: HelmRepository
        name: dwk-nats-helm
        namespace: flux-system
      interval: 10m